### ISSUE TITLE
Is there a way to calculate the appearance energy of the fragments from the files generated by QCxMS?

### ISSUE THREAD

**Issue by suriyaprasanths** [qcxms/QCxMS#69]

**Comment by gorges97** [comment]
In QCxMS, the appearance energies of the individual fragments are not directly computed. Since the energy distribution for the input molecule is only computed at the beginning for the individual trajectories and the total energy of the molecular dynamics simulations is not that clearly defined, as a reaction energy. At most, one could make "semi-quantitative" estimates for it from the IEE used for the trajectory in which a certain fragment is created. This information is printed in the setup step of the TMPQCXMS directory, so the second time you run qcxms.

However, we are currently working on a new method ("QCxMS2"), in which the spectrum is computed from the reaction barriers of the fragmentation reactions instead of MD simulations. Thus, appearance energies are directly accessible with this new approach.  Although I cannot provide a specific release date at the moment, we anticipate launching it this year.
